### ISSUE TITLE
Extract domain from concepts

### ISSUE THREAD

**Issue by HassanAkbar** [geolexica/isotc211-glossary#55]
As discussed here -> https://github.com/geolexica/isotc211.geolexica.org/issues/200#issuecomment-1768258038

We need to extract the domains from terms and add them to a the concept itself as a separate key

Currently the concepts are of the form

```yaml
terms:
  - type: expression
    normative_status: preferred
    designation: sibling cell <DGGS>
```

We need to transform it to

```yaml
domain: DGGS
terms:
  - type: expression
    normative_status: preferred
    designation: sibling cell
```
